swagger: "2.0"
    
info:
  title: Basic API for blog posts!
  description: Base api specification for what will become our posts application
  version: 0.0.1

consumes:
    - "application/json"
produces:
    - "application/json"

basePath: '/'

paths:
  /test:
    get:
      summary: Succeeds and Returns some blogposts, for testing.
      operationId: "blogpost.test"
      responses:
        '200':
          description: A basic array, for testing
          schema: 
            type: "array"
            items:
              properties:
                title:
                  type: "string"
                creator:
                  type: "string"
                body:
                  type: "string"
                creation_timestamp:
                  type: "string"
