swagger: "2.0"
    
info:
  title: Basic API for blog posts!
  description: Base api specification for what will become our posts application
  version: 0.0.1

consumes:
    - "application/json"
produces:
    - "application/json"

basePath: "/"

paths:
  /posts:
    get:
      summary: "Currently returns all blogposts, for testing."
      description: "TODO each call, should return the next bunch of posts, sorted by date."
      operationId: "blogpost.get_bunch_of_posts"
      tags:
          - "Blogposts"
      responses:
        "200":
          description: "A basic array, for testing"
          schema: 
            type: "array"
            items:
              properties:
                title:
                  type: "string"
                creator:
                  type: "string"
                body:
                  type: "string"
                creation_timestamp:
                  type: "string"
  /post:
    post:
      summary: "Creates a new blogpost."
      description: "TODO"
      operationId: "blogpost.create_new_post"
      tags:
          - "Blogposts"
      parameters:
        - name: blogpost
          in: body
          description: blogpost to create
          required: True
          schema:
            type: object
            properties:
              title:
                description: "title of the new blogpost"
                type: "string"
              creator:
                description: "name of the creator of this blogpost"
                type: "string"
              body:
                description: "body of the blogpost"
                type: "string"
      responses:
        "201":
          description: "Successful"
