swagger: "2.0"
    
info:
  title: Basic API for blog posts!
  description: Base api specification for what will become our posts application
  version: 0.0.1

consumes:
    - "application/json"
produces:
    - "application/json"

basePath: "/"

paths:
  /post:
    post:
      summary: "Creates a new blogpost."
      description: "TODO"
      operationId: "blogpost.create_new_post"
      tags:
          - "Blogposts"
      parameters:
        - name: blogpost
          in: body
          description: blogpost to create
          required: True
          schema:
            type: object
            properties:
              title:
                description: "title of the new blogpost"
                type: "string"
              creator:
                description: "name of the creator of this blogpost"
                type: "string"
              body:
                description: "body of the blogpost"
                type: "string"
      responses:
        "201":
          description: "Successful"
  /posts:
    get:
      summary: "Currently returns all blogposts, for testing."
      description: "TODO each call, should return the next bunch of posts, sorted by date."
      operationId: "blogpost.get_bunch_of_posts"
      tags:
          - "Blogposts"
      responses:
        "200":
          description: "An array with all the data of every blogpost in the bunch"
          schema: 
            type: "array"
            items:
              properties:
                title:
                  type: "string"
                creator:
                  type: "string"
                body:
                  type: "string"
                creation_timestamp:
                  type: "string"
  /postsnumber:
    get:
      summary: "Returns the total number of posts saved in the system"
      description: "count number of posts"
      operationId: "blogpost.get_number_of_posts"
      tags:
          - "Statistics"
      responses:
        "200":
          description: "A string describing the total number of posts"
          schema: 
            type: "string"

  /topcreators:
    get:
      summary: "Returns the 10 creators with the most posts"
      description: "Top 10 creators"
      operationId: "blogpost.get_top_creators"
      tags:
        - "Statistics"
      responses:
        "200":
          description: "array containing the name and number of posts for each creator"
          schema:
            type: "array"
            items:
              properties:
                creator:
                  type: "string"
                number_of_posts:
                  type: "integer"
