openapi: 3.0.0
    
info:
  title: Basic API
  description: Base api specification for what will become our posts application
  version: 0.0.1

paths:
  /test:
    get:
      summary: Succeeds and Returns nothing, for testing.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
